// Course data for DesignWiki

window.WIKI_DATA = [
  {
    id: "metodologia-especificacao",
    title: "Metodologia de Especificação",
    category: "Metodologia",
    sections: 12,
    updated: "Abr 2026",
    palette: ["#635BFF", "#00D4FF"],
    pattern: "rings",
  },
  {
    id: "metodologia-workshops",
    title: "Metodologia de Especificação",
    category: "Metodologia",
    sections: 8,
    updated: "Abr 2026",
    palette: ["#FF6B6B", "#C84BFF"],
    pattern: "grid",
  },
  {
    id: "metodologia-apresentacao",
    title: "Metodologia de Apresentação",
    category: "Metodologia",
    sections: 10,
    updated: "Abr 2026",
    palette: ["#F59E0B", "#EF4444"],
    pattern: "waves",
  },
  {
    id: "fluxograma",
    title: "Fluxograma",
    category: "Técnica",
    sections: 6,
    updated: "Fev 2026",
    palette: ["#10B981", "#0EA5E9"],
    pattern: "nodes",
  },
  {
    id: "atomic-design",
    title: "Atomic Design",
    category: "Framework",
    sections: 9,
    updated: "Jan 2026",
    palette: ["#8B5CF6", "#EC4899"],
    pattern: "atoms",
  },
  {
    id: "design-thinking",
    title: "Design Thinking",
    category: "Metodologia",
    sections: 11,
    updated: "Mar 2026",
    palette: ["#F97316", "#FACC15"],
    pattern: "rings",
  },
  {
    id: "double-diamond",
    title: "Double Diamond",
    category: "Framework",
    sections: 7,
    updated: "Dez 2025",
    palette: ["#06B6D4", "#3B82F6"],
    pattern: "diamonds",
  },
  {
    id: "jobs-to-be-done",
    title: "Jobs to Be Done",
    category: "Framework",
    sections: 8,
    updated: "Fev 2026",
    palette: ["#A855F7", "#6366F1"],
    pattern: "grid",
  },
  {
    id: "card-sorting",
    title: "Card Sorting",
    category: "Técnica",
    sections: 5,
    updated: "Jan 2026",
    palette: ["#EC4899", "#F43F5E"],
    pattern: "stack",
  },
  {
    id: "user-journey",
    title: "User Journey Mapping",
    category: "Técnica",
    sections: 7,
    updated: "Mar 2026",
    palette: ["#14B8A6", "#22D3EE"],
    pattern: "waves",
  },
  {
    id: "heuristic-evaluation",
    title: "Avaliação Heurística",
    category: "Técnica",
    sections: 9,
    updated: "Abr 2026",
    palette: ["#F59E0B", "#EAB308"],
    pattern: "nodes",
  },
  {
    id: "design-sprint",
    title: "Design Sprint",
    category: "Framework",
    sections: 14,
    updated: "Mar 2026",
    palette: ["#3B82F6", "#8B5CF6"],
    pattern: "diamonds",
  },
];

window.CATEGORIES = ["Tudo", "Técnica", "Metodologia", "Framework"];
