// Content for "Especificação de Requisitos" — full text from PDFs (when available)
// Each chapter is structured as blocks: { type, ... }
// Block types: "p" (paragraph), "h2", "h3", "list" (ul with seta items),
//   "callout" (highlight box), "quote" (italic narrative scenario),
//   "table" ({headers, rows}), "two-col" ({left, right}), "diagram" (svg id),
//   "divider"

window.SPEC_CHAPTERS = [
  {
    id: "introducao",
    eyebrow: "ESPECIFICAÇÃO DE REQUISITOS",
    title: "Introdução",
    blocks: [
      { type: "p", text: "Toda interface bonita esconde uma camada que ninguém vê: as decisões que ditam como ela se comporta. É essa camada que separa um Figma elogiado de um produto que entrega valor. Especificar requisitos é o trabalho de tornar essas decisões explícitas — antes de virarem dúvida no sprint, retrabalho no QA ou desalinhamento na review." },
      { type: "p", text: "Esta seção da DesignWiki existe para que designers, POs e devs partam do mesmo vocabulário e do mesmo processo. Não é teoria de prateleira — é o que usamos no dia a dia da Mirai para reduzir ambiguidade e aumentar previsibilidade." },
      { type: "callout", icon: "💡", text: "Especificar não é escrever mais. É escrever o que o protótipo não consegue dizer sozinho." },
      { type: "h2", text: "O que você vai encontrar aqui" },
      { type: "list", items: [
        "O vocabulário fundamental: regras de negócio, requisitos, histórias e critérios de aceite",
        "Critérios objetivos para decidir o quanto documentar",
        "O Framework CERVE — cinco etapas para conduzir uma especificação do começo ao fim",
        "Um exemplo aplicado de ponta a ponta, do briefing ao backlog",
        "FAQ com as dúvidas mais comuns no dia a dia",
      ]},
      { type: "h2", text: "Como ler" },
      { type: "p", text: "As seções foram organizadas em ordem de uso. Se é a primeira vez que você abre essa documentação, comece por Regras e Requisitos e siga em sequência. Se já conhece o vocabulário, pule direto para o Framework CERVE — é onde a prática acontece." },
      { type: "p", html: 'Cada seção termina com uma ponte para a próxima. Use o menu lateral à esquerda para pular entre capítulos a qualquer momento.' },
    ],
  },
  {
    id: "regras-requisitos",
    eyebrow: "FUNDAMENTOS",
    title: "Regras e Requisitos",
    blocks: [
      { type: "p", text: "Antes de entrar em qualquer metodologia, você precisa ter o vocabulário certo. Não porque terminologia seja bonita em slide, mas porque quando todo mundo no projeto usa as mesmas palavras com significados diferentes, o resultado é reunião, retrabalho e aquela sensação de que \"a gente já alinhou isso antes\"." },
      { type: "p", text: "Então vamos começar pelo que existe antes de qualquer sistema." },
      { type: "h2", text: "Regras de negócio: a camada que ninguém vê nas telas" },
      { type: "p", text: "Toda empresa funciona por um conjunto de condições que definem o que pode e o que não pode ser feito. Essas condições existem com ou sem tecnologia, com ou sem software, com ou sem designer envolvido. Elas são as regras de negócio." },
      { type: "callout", icon: "💡", text: "Regras de negócio são as exigências, condições ou restrições que definem como o negócio opera, independentemente de haver um sistema de software ou não. Elas estabelecem o que é correto, o que é permitido e o que é proibido dentro de uma operação." },
      { type: "p", html: "Um teste prático que funciona bem: imagine o negócio rodando apenas com papel e caneta. <strong>As regras que continuariam valendo são regras de negócio.</strong>" },
      { type: "h3", text: "Alguns exemplos concretos:" },
      { type: "list", items: [
        "“Produtos só são entregues ao cliente após a confirmação do pagamento.”",
        "“Clientes que compram quatro sacos de ração ganham o quinto de graça.”",
        "“Se o salário for maior que R$ 3.500, a taxa de imposto é de 25%.”",
      ]},
      { type: "p", text: "Nenhuma dessas frases menciona sistema, tela, botão ou fluxo. Elas valeriam num processo inteiramente manual da mesma forma que valem num sistema automatizado. E elas continuam válidas mesmo depois que o projeto termina ou mesmo depois que a tecnologia muda." },
      { type: "p", html: 'Nas conversas com stakeholders, fique atento a certas <em class="accent">palavras de alerta</em>, como “sempre”, “nunca”, “obrigatoriamente”, “somente se”, “pode/não pode”. Quando você ouvir essas palavras, provavelmente tem uma regra de negócio no meio da fala.' },

      { type: "h2", text: "A história da mãe e da filha" },
      { type: "p", text: "Entender regras de negócio é relativamente fácil. O que confunde de verdade é a relação entre elas e os requisitos. E existe uma analogia que circula há anos na literatura de análise de negócios que nos ajuda a entender melhor:" },
      { type: "quote", text: "Imagine uma mãe e sua filha de 18 anos, que acabou de tirar a carteira de motorista. A mãe estabelece as condições da casa: a filha nunca pode chegar depois das 22h30, e nunca pode aceitar carona de desconhecidos. A filha ouve tudo, concorda com as condições, mas apresenta a sua proposta: ela quer um carro próprio." },
      { type: "p", html: "<strong>O que aconteceu aqui?</strong> A mãe definiu as regras. A filha apresentou um requisito." },
      { type: "p", text: "O carro é a solução que permite à filha cumprir a regra de horário. Mas a regra não mudou. Se ela voltar de ônibus, de Uber ou a pé, a obrigação de estar em casa às 22h30 continua idêntica. A regra é independente de qualquer solução. O requisito é apenas uma forma de viabilizá-la." },
      { type: "p", html: 'Essa distinção tem uma implicação prática enorme: <em class="accent">regras de negócio têm alta estabilidade, requisitos têm alta volatilidade</em>. A regra de que o pagamento precisa ser confirmado antes da entrega provavelmente não muda no próximo sprint. Mas a forma como o sistema implementa isso, os critérios exatos, as mensagens, os estados intermediários, tudo isso pode ser revisado e ajustado ao longo do projeto.' },

      { type: "h2", text: "O que é um requisito, então?" },
      { type: "p", html: "Ian Sommerville, em <em>Software Engineering</em>, define requisitos como “as descrições do que o sistema deve fazer, os serviços que oferece e as restrições ao seu funcionamento”." },
      { type: "p", html: "Pra quem trabalha com produto, uma definição mais útil pode ser: <strong>requisitos são decisões sobre como a solução deve funcionar para atender uma necessidade.</strong> É uma decisão documentada que orienta design, desenvolvimento e QA sobre o que precisa ser verdade quando o produto estiver rodando." },

      { type: "h2", text: "Os 2 tipos de requisito que você vai encontrar no dia a dia" },
      { type: "p", text: "O IIBA (International Institute of Business Analysis), no seu guia BABOK, organiza os requisitos em camadas que vão do estratégico ao operacional. Na prática do trabalho de produto da Mirai, você vai encontrar principalmente:" },
      { type: "two-col",
        left: { kicker: "Funcional", title: "O que o sistema faz", body: "São as ações concretas que o produto precisa ser capaz de executar. “Enviar lembrete automático de pagamento três dias antes do vencimento” é um requisito funcional. É daqui que a maioria das histórias de usuário nasce, com suas condições de aceite específicas." },
        right: { kicker: "Não funcional", title: "Como bem ele faz", body: "Qualidade, performance, segurança, disponibilidade. “O lembrete deve ser disparado em até 5 minutos, com 99,5% de disponibilidade” é não funcional. Ele não descreve uma funcionalidade nova, mas define a régua que aquela funcionalidade precisa atingir." },
      },

      { type: "h2", text: "Dicas rápidas: Regras x Requisitos" },
      { type: "p", text: "A confusão entre esses dois conceitos é a mais comum em projetos de produto. Aqui estão os atalhos práticos para não misturar os dois." },
      { type: "h3", text: "Como identificar uma regra de negócio na conversa" },
      { type: "p", text: "Fique atento a essas palavras nas falas dos stakeholders. Elas quase sempre indicam que tem uma regra por trás:" },
      { type: "list", items: [
        "<strong>“Sempre” e “nunca”</strong> — “o sistema nunca pode aprovar um pedido sem estoque confirmado”",
        "<strong>“Obrigatoriamente” e “somente se”</strong> — “somente o supervisor pode estornar um pagamento”",
        "<strong>“Pode/não pode”</strong> — “o usuário não pode ter dois cadastros com o mesmo CPF”",
        "<strong>“Tem que” e “precisa ter”</strong> — “todo contrato tem que ter assinatura do responsável financeiro”",
      ]},
      { type: "p", text: "Se a frase descreve uma condição que o negócio impõe, é uma regra. Documente-a separada dos requisitos." },

      { type: "h3", text: "O teste rápido na dúvida" },
      { type: "p", text: "Antes de classificar qualquer coisa, aplique uma das duas perguntas:" },
      { type: "list", items: [
        "<strong>“Isso valeria se o processo fosse feito só com papel e caneta?”</strong> Se sim, é regra de negócio.",
        "<strong>“Isso só existe porque há um sistema?”</strong> Se sim, é requisito.",
      ]},

      { type: "h3", text: "Os erros mais comuns" },
      { type: "p", html: "<strong>Colocar a regra como requisito funcional.</strong> A consequência prática: no próximo refinamento, alguém vai questionar aquilo como se fosse negociável, quando nunca esteve em aberto. Regra de negócio fica numa camada separada, acima dos requisitos." },
      { type: "p", html: "<strong>Achar que toda regra vira um requisito.</strong> Uma regra de negócio pode gerar vários requisitos, pode aparecer como critério de aceite ou pode simplesmente precisar estar documentada como restrição de contexto. A relação não é de um para um." },
      { type: "callout", icon: "💡", text: "A regra define o que o negócio exige. O requisito descreve o que o sistema faz para cumprir essa exigência." },

      { type: "p", text: "Até aqui você tem os dois conceitos centrais de qualquer especificação: as regras que o negócio impõe e os requisitos que traduzem essas regras em comportamento de sistema. Mas dentro do universo dos requisitos, existe ainda uma camada que conecta tudo isso ao trabalho concreto do dia a dia, às histórias de usuário e aos critérios que definem quando algo está realmente pronto. É sobre isso que falamos a seguir." },
    ],
  },
  {
    id: "historias-criterios",
    eyebrow: "FUNDAMENTOS",
    title: "Histórias e Critérios de Aceite",
    blocks: [
      { type: "p", text: "Regras e requisitos são a base. Mas é nas histórias de usuário e nos critérios de aceite que o trabalho de especificação se torna acionável para o time de desenvolvimento. Esta seção mostra como traduzir requisitos em histórias bem escritas e em critérios que possam ser testados." },
      { type: "h2", text: "História de usuário: a unidade de valor" },
      { type: "p", text: "Uma história de usuário é a menor unidade de funcionalidade que entrega valor para alguém. Ela não descreve uma tela ou um botão — descreve uma necessidade que precisa ser atendida." },
      { type: "callout", icon: "💡", text: "Como [usuário], quero [ação], para que [benefício]." },
      { type: "p", text: "Esse formato é simples de propósito. Ele força quem escreve a deixar três coisas explícitas: quem, o quê e por quê. Se algum dos três está faltando ou vago, a história ainda não está pronta para ser estimada." },
      { type: "h2", text: "Critérios de aceite: quando a história está concluída" },
      { type: "p", text: "Critérios de aceite são as condições testáveis que precisam ser verdadeiras para que a história seja considerada entregue. Não são desejos. São observações que QA, design e dev podem verificar de forma objetiva." },
      { type: "p", html: "O formato mais usado é o <strong>Given / When / Then</strong> do BDD: dado um contexto, quando uma ação acontece, então o sistema responde de determinada forma." },
      { type: "two-col",
        left: { kicker: "❌ Vago", title: "“O botão deve ser intuitivo”", body: "Não é testável. O que significa intuitivo? Para quem? Em que momento?" },
        right: { kicker: "✅ Testável", title: "“O botão só fica ativo quando todos os campos obrigatórios estiverem preenchidos”", body: "QA pode verificar isso em segundos. Dev sabe exatamente o que implementar." },
      },
      { type: "h2", text: "Quantos critérios uma história deve ter?" },
      { type: "p", text: "O suficiente para cobrir o caminho feliz, os principais fluxos alternativos e os erros mais prováveis. Na prática, entre três e seis costuma ser um intervalo saudável. Se você está passando de oito, provavelmente a história está grande demais e precisa ser fatiada." },
      { type: "p", text: "Histórias bem escritas e critérios claros são o que permite que o time avance sem precisar adivinhar. Mas saber escrever uma história não responde a pergunta mais difícil de toda especificação: quanto preciso documentar? É sobre isso que falamos a seguir." },
    ],
    placeholder: true,
  },
  {
    id: "documentar",
    eyebrow: "PRÁTICA",
    title: "O que Documentar",
    blocks: [
      { type: "p", text: "Você chegou até aqui sabendo o que são regras de negócio, requisitos, histórias de usuário e critérios de aceite. O vocabulário está claro. Mas agora vem a pergunta que aparece toda vez que alguém senta para especificar de verdade:" },
      { type: "callout", icon: "❓", text: "Quanto eu preciso escrever?" },
      { type: "p", text: "Escrever de menos gera ambiguidade, dando margem para implementações diferentes porque “achei que era assim”. Escrever demais gera documentação que ninguém lê, fica desatualizada em dois sprints e dá a falsa sensação de que o projeto está protegido quando não está." },
      { type: "p", html: "O equilíbrio tem nome na literatura ágil: <em>just enough documentation</em>. A mínima viável que permite ao time construir o produto certo de forma eficiente." },
      { type: "h2", text: "O que as telas já documentam por você" },
      { type: "p", html: 'A tela cobre o <strong>“como parece”</strong>. Layout, hierarquia visual, componentes, fluxo de navegação. Redocumentar o que já está visível é desperdício.' },
      { type: "p", html: 'O que a tela <strong>não</strong> cobre é o <strong>“como se comporta”</strong>. Comportamentos condicionais, estados do sistema, fluxos de erro, regras de negócio por trás de algo que parece visual, permissões que mudam o que o usuário vê. Tudo isso é invisível num protótipo estático. É exatamente isso que precisa ser escrito.' },
      { type: "h2", text: "Como saber o quanto documentar" },
      { type: "h3", text: "Passo 1 — Conheça quem vai ler antes de escrever" },
      { type: "p", text: "O nível de detalhe necessário depende diretamente de quem vai construir. Antes de especificar com um dev novo, vale uma pergunta direta: “Quando você recebe uma história com uma lacuna, o que você faz?”" },
      { type: "p", text: "Você vai encontrar basicamente três perfis:" },
      { type: "list", items: [
        "<strong>O inferidor</strong> preenche as lacunas sozinho. Documente apenas o que ele genuinamente não teria como adivinhar.",
        "<strong>O perguntador</strong> para e te chama antes de implementar. Antecipe as dúvidas prováveis e responda antes que elas apareçam.",
        "<strong>O literal</strong> implementa exatamente o que está escrito. Se não está escrito, não existe. Para ele, implícito não é suficiente.",
      ]},
      { type: "p", text: "Você não vai mudar o perfil do desenvolvedor. Você vai adaptar sua documentação a ele." },

      { type: "h3", text: "Passo 2 — Pergunte o que a tela não responde" },
      { type: "p", html: "Para cada tela ou componente, aplique a pergunta gatilho: <em class='accent'>o que está acontecendo aqui que um desenvolvedor não consegue ver?</em>" },
      { type: "table",
        headers: ["Categoria", "Pergunta prática", "Exemplo do que documentar"],
        rows: [
          ["Estados do sistema", "Essa tela tem mais de uma versão dependendo de uma condição?", "“Botão desabilitado enquanto o campo estiver vazio”"],
          ["Erros e exceções", "O que acontece quando algo dá errado?", "“Se a API falhar, exibir mensagem X e manter os dados preenchidos”"],
          ["Regras de negócio", "Há uma lógica por trás de algo que parece visual?", "“Só usuários com perfil Admin veem esse campo”"],
          ["Fluxos alternativos", "Existe um caminho que o usuário pode tomar que não está prototipado?", "“Se o usuário já tiver conta, pular etapa 2”"],
          ["Dependências de sistema", "Esse comportamento depende de outro sistema, API ou serviço?", "“O status é atualizado em tempo real via webhook”"],
          ["Timing e assincronismo", "Tem carregamento, delay, polling ou atualização automática?", "“Lista recarrega a cada 30 segundos automaticamente”"],
          ["Permissões e contexto", "O comportamento muda dependendo de quem está usando?", "“Usuário free não consegue clicar, vê tooltip de upgrade”"],
        ],
      },
      { type: "p", text: "Não pense no que você sabe. Pense no que está invisível. Se a tela já responde claramente, não precisa de texto. Se exige conhecimento de negócio, estado do sistema ou regra que não aparece na interface, precisa. Uma ferramenta que pode ajudar bastante nisso é o checklist DIREC, disponível na biblioteca de técnicas da DesignWiki." },

      { type: "h3", text: "Passo 3 — Aplique o teste do “consegue testar?”" },
      { type: "p", html: "Para cada item que levantou no passo anterior, pergunte: <em class='accent'>o QA consegue verificar se isso foi implementado corretamente só olhando o Figma?</em>" },
      { type: "p", html: "Se sim, apaga. Se a resposta exigir uma frase de comportamento — “quando X acontece, o sistema faz Y” — mantém." },

      { type: "h3", text: "Passo 4 — Escreva comportamento, não intenção" },
      { type: "p", html: "Quando algo precisa ser documentado, a forma importa. Não escreva o que você quer, escreva o que o sistema faz. A estrutura que funciona é simples: <strong>quando [condição], o sistema [faz X]</strong>." },
      { type: "table",
        headers: ["❌ Evitar", "✅ Preferir"],
        rows: [
          ["“O botão deve ser intuitivo”", "“O botão só fica ativo quando todos os campos obrigatórios estiverem preenchidos”"],
          ["“Tratar erro de forma amigável”", "“Se a requisição falhar, exibir: ‘Não foi possível salvar. Tente novamente.’”"],
          ["“Respeitar hierarquia de usuários”", "“Usuários com perfil Viewer não veem o botão Editar”"],
        ],
      },

      { type: "h3", text: "Passo 5 — Calibre com cada entrega" },
      { type: "p", text: "O nível certo não é fixo. Se algo foi implementado diferente do esperado, você documentou pouco ou a frase ficou ambígua. Se o dev perguntou algo que estava escrito, a frase não estava clara o suficiente. Se perguntou algo que não estava, adicione essa categoria ao seu radar." },
      { type: "p", text: "Com três ou quatro histórias entregues, você já tem o nível calibrado para aquela pessoa. Quando o time mudar, você começa de novo, mas com muito mais consciência do processo." },

      { type: "p", text: "Saber o que documentar resolve metade do problema. A outra metade é estruturar o processo de especificação do começo ao fim, de forma que nenhuma decisão importante fique pra trás. É exatamente isso que o Framework CERVE propõe, e é o que veremos a seguir." },
    ],
  },
];

window.SPEC_CHAPTERS_PT2 = [
  {
    id: "cerve",
    eyebrow: "FRAMEWORK CERVE",
    title: "Framework CERVE",
    blocks: [
      { type: "p", text: "Você tem o vocabulário certo. Sabe o que são regras de negócio, requisitos, histórias e critérios de aceite. Sabe o que documentar e o quanto documentar. O que falta agora é um processo. Uma sequência que organize o trabalho de especificação do começo ao fim, sem deixar decisão importante cair no meio do caminho." },
      { type: "p", html: "O Framework CERVE é isso. Cinco etapas que levam o projeto desde a compreensão do problema até o backlog pronto para desenvolvimento. O nome é um acrônimo: <strong class='accent'>C</strong>ontextualizar, <strong class='accent'>E</strong>licitar, <strong class='accent'>R</strong>efinar, <strong class='accent'>V</strong>alidar e <strong class='accent'>E</strong>specificar." },
      { type: "diagram", id: "cerve" },
      { type: "p", html: "Para ilustrar cada etapa, vamos usar o mesmo exemplo ao longo de toda a seção: <em>o desenvolvimento de um módulo de emissão de segunda via de boleto para uma plataforma educacional.</em>" },

      { type: "stage", letter: "C", name: "Contextualizar", desc: "Entender profundamente o problema antes de qualquer solução." },
      { type: "p", text: "Essa é a etapa mais ignorada e a mais cara de ignorar. Quando um projeto começa pela solução, tudo que vier depois estará tentando acertar um alvo que ainda não foi bem definido. Contextualizar é construir a base: o porquê do projeto, o que está em jogo, quais são os limites e o que já se sabe antes de conversar com qualquer stakeholder." },
      { type: "h3", text: "Ferramentas e atividades" },
      { type: "list", items: [
        "<strong>Entrevistas com stakeholders:</strong> conversas estruturadas para entender objetivos, restrições e expectativas de quem tem autoridade sobre o negócio",
        "<strong>Briefing do projeto:</strong> documento inicial que registra escopo, contexto, prazo e principais envolvidos",
        "<strong>Análise de documentação existente:</strong> leitura de materiais já produzidos sobre o domínio: processos, contratos, manuais, sistemas legados",
        "<strong>Workshops de alinhamento:</strong> sessões colaborativas para construir entendimento compartilhado entre áreas diferentes",
      ]},
      { type: "h3", text: "Resultado esperado" },
      { type: "list", items: [
        "Objetivos de negócio claros",
        "Problema definido com precisão",
        "Lista de Certezas, Suposições e Dúvidas",
      ]},
      { type: "quote", text: "A plataforma recebe um volume alto de chamados no suporte sobre boletos vencidos. O objetivo de negócio é reduzir esse volume em 40% nos próximos dois trimestres. Antes de qualquer reunião de requisitos, o time registra o que já sabe (certeza: os boletos expiram em 3 dias úteis), o que está supondo (suposição: a maioria dos alunos acessa a plataforma pelo celular) e o que precisa descobrir (dúvida: quem tem permissão para emitir a segunda via, só o aluno ou também o responsável financeiro?)." },

      { type: "stage", letter: "E", name: "Elicitar", desc: "Coletar informações do mundo real sobre como o processo funciona hoje." },
      { type: "p", text: "Elicitar é sair da opinião e ir para a realidade operacional. É a etapa em que você para de imaginar como o negócio funciona e começa a descobrir como ele de fato funciona. Cada conversa com um stakeholder nessa fase é uma oportunidade de encontrar uma regra de negócio que ninguém havia explicitado, um fluxo que acontece na prática mas não está em lugar nenhum, uma dor que o projeto precisa resolver mas que ainda não tinha nome." },
      { type: "h3", text: "Ferramentas e atividades" },
      { type: "list", items: [
        "<strong>Entrevistas e workshops com stakeholders:</strong> conversas focadas em extrair como o processo funciona hoje, quais são as dores e o que precisa mudar",
        "<strong>Análise de sistemas existentes:</strong> investigação de como sistemas atuais se comportam, quais regras já estão implementadas e onde estão as lacunas",
        "<strong>Fluxogramas do processo atual:</strong> mapeamento visual do fluxo real de trabalho, antes de qualquer solução proposta",
        "<strong>Cenários narrativos:</strong> descrições em prosa de como um usuário real percorre uma situação de ponta a ponta, incluindo contexto, motivação e o que acontece quando algo dá errado",
        "<strong>Uso de IA:</strong> com o contexto do projeto em mãos, usar modelos de linguagem como segundo par de olhos analítico que questiona o que ainda não foi pensado",
        "<strong>Benchmarking:</strong> análise de como produtos similares resolvem o mesmo problema",
        "<strong>Prototipação exploratória:</strong> esboços rápidos usados não para validar solução, mas para provocar reação e extrair informação",
        "<strong>Diagrama de Caso de Uso:</strong> representação UML que descreve as funcionalidades de um sistema e as interações entre seus usuários e o software",
      ]},
      { type: "h3", text: "Resultado esperado" },
      { type: "list", items: [
        "Necessidades e dores levantadas",
        "Lista inicial de requisitos funcionais e não funcionais",
        "Lista de Certezas, Suposições e Dúvidas atualizada",
      ]},
      { type: "quote", text: "Nas entrevistas com o time de suporte, o time descobre que alunos inadimplentes há mais de 60 dias não podem emitir segunda via sem autorização da coordenação financeira. Ninguém tinha mencionado essa restrição antes. Ela é uma regra de negócio que precisará guiar pelo menos dois requisitos funcionais novos." },

      { type: "stage", letter: "R", name: "Refinar", desc: "Transformar informação bruta em estrutura." },
      { type: "p", text: "Depois de elicitar, você tem muito material. Anotações de entrevistas, fluxos rabiscados, requisitos jogados em lista sem categoria, dúvidas que viraram certezas e certezas que viraram dúvidas. Refinar é a etapa mais analítica do processo. É aqui que você organiza, classifica, questiona e, principalmente, explicita as regras de negócio que estavam escondidas nas conversas." },
      { type: "p", html: "Duas ferramentas são especialmente úteis nessa etapa. O <strong>Checklist DIREC</strong> ajuda a garantir que cada componente foi entendido de ponta a ponta, passando por Dados, Interações, Regras, Estados e Contexto. A <strong>técnica “E se?”</strong> força o fluxo feliz a mostrar suas bordas: cada “e se?” sem resposta é um requisito escondido esperando para aparecer no meio do desenvolvimento." },
      { type: "h3", text: "Resultado esperado" },
      { type: "list", items: [
        "Lista de requisitos organizada e categorizada",
        "Estrutura inicial de backlog",
        "Lista de Certezas, Suposições e Dúvidas revisada",
      ]},
      { type: "quote", text: "Ao passar o Checklist DIREC pelo componente de emissão de boleto, o time percebe que nenhuma das entrevistas respondeu o que acontece quando o gateway de pagamento está fora do ar no momento da geração. A técnica “E se?” revela mais três cenários não mapeados." },

      { type: "stage", letter: "V", name: "Validar", desc: "Garantir que o entendimento está correto antes de seguir." },
      { type: "p", text: "Validar é trocar “acho que entendi” por “estamos alinhados”. É a etapa em que você leva o que foi refinado de volta para quem tem autoridade sobre o negócio e confirma, com exemplos e cenários concretos, que o entendimento está correto. Erros encontrados aqui custam uma reunião. Erros encontrados depois do desenvolvimento custam sprints inteiros." },
      { type: "h3", text: "Ferramentas e atividades" },
      { type: "list", items: [
        "<strong>Playback com stakeholders</strong>",
        "<strong>Walkthrough de fluxos</strong>",
        "<strong>Prototipação de baixa ou média fidelidade</strong>",
        "<strong>Simulação de casos de uso reais</strong>",
        "<strong>Revisão de regras de negócio e exceções</strong>",
      ]},
      { type: "quote", text: "Durante o walkthrough com a coordenação financeira, o time apresenta o fluxo completo incluindo a regra de bloqueio para inadimplentes acima de 60 dias. A coordenadora corrige: o prazo correto é 45 dias, não 60. Sem essa validação, o requisito teria sido especificado com uma regra errada." },

      { type: "stage", letter: "E", name: "Especificar", desc: "Traduzir tudo em algo acionável para design, desenvolvimento e QA." },
      { type: "p", text: "A última etapa é onde o trabalho analítico se torna execução. Especificar é pegar tudo que foi contextualizado, elicitado, refinado e validado e transformar em histórias claras, com critérios testáveis, prontas para entrar no backlog." },
      { type: "h3", text: "Ferramentas e atividades" },
      { type: "list", items: [
        "<strong>Escrita de histórias de usuário</strong> no formato “Como [usuário], quero [ação], para que [benefício]”",
        "<strong>Definição de critérios de aceite</strong> testáveis",
        "<strong>BDD com estrutura Given / When / Then</strong>",
        "<strong>User story mapping e fatiamento</strong>",
        "<strong>Definition of Ready</strong>",
      ]},
      { type: "quote", text: "O requisito “emitir segunda via de boleto” vira a história “Como aluno com parcela em aberto, quero gerar uma segunda via do boleto para conseguir efetuar o pagamento mesmo após o vencimento.”" },

      { type: "callout", icon: "💡", text: "O CERVE não é um processo linear rígido. Você vai descobrir durante o refinamento que precisa voltar a elicitar. Vai encontrar na validação uma regra que exige um novo ciclo de refino. Isso é esperado e saudável. O que o framework garante é que nenhuma etapa seja simplesmente pulada." },
      { type: "p", text: "Na próxima seção, você vai ver esse processo funcionando em exemplos reais de projetos." },
    ],
  },
  {
    id: "exemplo",
    eyebrow: "APLICAÇÃO",
    title: "Exemplo de Aplicação",
    blocks: [
      { type: "p", text: "Teoria sem prática é slide de aula. Esta seção mostra o Framework CERVE rodando do começo ao fim em um projeto real: a emissão de segunda via de boleto para uma plataforma educacional, o mesmo exemplo usado nas seções anteriores." },
      { type: "h2", text: "Briefing do projeto" },
      { type: "p", text: "A plataforma recebe um volume alto de chamados no suporte sobre boletos vencidos. O objetivo de negócio é reduzir esse volume em 40% nos próximos dois trimestres, dando autonomia ao aluno para emitir a segunda via sem depender da secretaria." },
      { type: "h2", text: "Etapa 1 — Contextualizar" },
      { type: "p", text: "O time inicia com entrevistas com a coordenação financeira, o time de suporte e dois alunos representativos. Documenta certezas, suposições e dúvidas, identifica restrições legais (cobrança regulada) e técnicas (integração com gateway terceiro)." },
      { type: "h2", text: "Etapa 2 — Elicitar" },
      { type: "p", text: "Em workshops com a coordenação, surgem regras que não estavam em nenhum manual: bloqueio para inadimplentes acima de 45 dias, necessidade de aprovação da secretaria para reabrir parcelas, taxa de boleto recalculada após o vencimento. Cenários narrativos descrevem a jornada de uma aluna que tenta pagar à noite no celular." },
      { type: "h2", text: "Etapa 3 — Refinar" },
      { type: "p", text: "O Checklist DIREC é aplicado ao componente de emissão. A técnica “E se?” descobre três cenários críticos: gateway fora do ar, boleto não chegando por e-mail e parcela paga ainda aparecendo como pendente." },
      { type: "h2", text: "Etapa 4 — Validar" },
      { type: "p", text: "O fluxo completo é apresentado em walkthrough para a coordenação. Correções são incorporadas: prazo de bloqueio ajustado de 60 para 45 dias, desbloqueio descentralizado para a secretaria." },
      { type: "h2", text: "Etapa 5 — Especificar" },
      { type: "p", html: 'A história principal: <em>"Como aluno com parcela em aberto, quero gerar uma segunda via do boleto para conseguir efetuar o pagamento mesmo após o vencimento."</em> Critérios de aceite cobrem o caminho feliz, o bloqueio por inadimplência e o tratamento de erros do gateway.' },
      { type: "callout", icon: "🎯", text: "Resultado: backlog com 12 histórias, 47 critérios de aceite e 9 regras de negócio explicitadas — entregue ao desenvolvimento sem ambiguidade." },
    ],
    placeholder: true,
  },
  {
    id: "faq",
    eyebrow: "FAQ",
    title: "Perguntas Frequentes",
    blocks: [
      { type: "h2", text: "De quem é a responsabilidade de especificar?" },
      { type: "p", text: "Depende do time, mas na prática quem desenha a interface é quem mais entende o comportamento que precisa estar documentado. Cada componente implica uma decisão de como o sistema deve agir. Se o designer não especifica esse comportamento, alguém vai especificar no lugar dele, geralmente o dev, no meio do sprint, sem contexto de negócio. Em times com PO ou BA, a especificação é colaborativa. Mas esperar que outra pessoa cuide disso sozinha é abrir mão de influência sobre o produto que você está desenhando." },
      { type: "h2", text: "Como eu sei quando uma informação é uma regra de negócio e quando é um requisito?" },
      { type: "p", html: 'Aplique o teste do papel e caneta: se a regra continuaria valendo num processo inteiramente manual, sem nenhum sistema, é uma regra de negócio. <em>"Consultas de especialidade exigem consulta clínica prévia"</em> vale no papel, no WhatsApp e no sistema. É uma regra. <em>"O sistema deve verificar o histórico do paciente antes de liberar o agendamento"</em> só existe porque há um sistema. É um requisito.' },
      { type: "h2", text: "Tenho pouco tempo no projeto. Preciso mesmo seguir as cinco etapas do CERVE?" },
      { type: "p", html: 'O CERVE não é burocracia, é uma sequência lógica. Você pode percorrê-la de forma mais rápida ou mais profunda dependendo da complexidade do projeto, mas pular etapas tem um custo previsível: o que não foi contextualizado vai gerar retrabalho no refinamento, o que não foi validado vai aparecer errado no desenvolvimento. A pergunta não é <em>"tenho tempo para o CERVE?"</em> É <em>"tenho tempo para corrigir o que vai quebrar se eu pular?"</em>' },
      { type: "h2", text: "O stakeholder não sabe explicar o que quer. Como eu elicito requisitos assim?" },
      { type: "p", text: "Esse é o cenário mais comum e, paradoxalmente, onde a elicitação tem mais valor. Quando o stakeholder não consegue descrever o que quer em abstrato, mude o ângulo: peça para ele descrever como o processo funciona hoje, o que dá mais trabalho, o que ele faz de diferente dependendo da situação. As regras de negócio estão escondidas nessas respostas. Cenários narrativos e prototipações de baixa fidelidade também ajudam muito: é mais fácil reagir a algo concreto do que descrever algo do zero." },
      { type: "h2", text: "Qual a diferença entre critério de aceite e Definition of Done?" },
      { type: "p", text: "Critérios de aceite são específicos de uma história: definem quando aquela funcionalidade em particular foi entregue corretamente. A Definition of Done é uma régua global que se aplica a todas as histórias sem exceção, geralmente envolvendo qualidade técnica, como code review, testes automatizados e acessibilidade. Uma história pode passar nos próprios critérios de aceite e ainda assim não estar “done” se não cumprir a Definition of Done do time." },
      { type: "h2", text: "Quantos critérios de aceite uma história deve ter?" },
      { type: "p", text: "O suficiente para cobrir o caminho feliz, os principais fluxos alternativos e os erros mais prováveis. Na prática, entre três e seis costuma ser um intervalo saudável. Se você está passando de oito, provavelmente a história está grande demais e precisa ser fatiada. Se tem só um, provavelmente há comportamentos implícitos que ainda não foram explicitados." },
      { type: "h2", text: "Eu já entrego protótipos detalhados no Figma. Isso não é suficiente?" },
      { type: "p", html: 'O protótipo cobre o <strong>"como parece"</strong>. O que ele não responde são os comportamentos condicionais, os estados de erro, as regras de negócio invisíveis na interface e tudo que depende de contexto do sistema para acontecer. Um botão desabilitado no Figma não explica quando ele habilita. Uma mensagem de erro no protótipo não diz o que a dispara. A especificação existe exatamente para preencher essa lacuna, não para substituir o Figma, mas para completar o que ele não consegue comunicar sozinho.' },
    ],
  },
  {
    id: "referencias",
    eyebrow: "BIBLIOTECA",
    title: "Referências",
    blocks: [
      { type: "p", text: "A literatura por trás desta seção. Leituras recomendadas para quem quer aprofundar cada tópico." },
      { type: "h2", text: "Livros fundamentais" },
      { type: "list", items: [
        "<strong>Software Engineering</strong> — Ian Sommerville. A definição clássica de requisitos, ainda referência em qualquer curso de engenharia de software.",
        "<strong>BABOK Guide</strong> — IIBA (International Institute of Business Analysis). O guia mais completo sobre análise de negócios e classificação de requisitos.",
        "<strong>User Story Mapping</strong> — Jeff Patton. Como organizar histórias em sequência de uso e identificar dependências e prioridades.",
        "<strong>Specification by Example</strong> — Gojko Adzic. A prática de especificar usando exemplos concretos como base para BDD e testes.",
      ]},
      { type: "h2", text: "Artigos e referências online" },
      { type: "list", items: [
        "<strong>Just Barely Good Enough</strong> — Scott Ambler. O conceito de just enough documentation aplicado ao trabalho ágil.",
        "<strong>Behavior-Driven Development</strong> — Dan North. O artigo seminal sobre BDD e a estrutura Given/When/Then.",
        "<strong>The Three Amigos</strong> — George Dinwiddie. A prática de PO, dev e QA refinarem juntos antes do sprint.",
      ]},
      { type: "h2", text: "Ferramentas relacionadas na DesignWiki" },
      { type: "list", items: [
        "<strong>Checklist DIREC</strong> — Cinco lentes (Dados, Interações, Regras, Estados, Contexto) para análise de componentes",
        "<strong>Técnica E Se?</strong> — Perguntas sistemáticas para descobrir requisitos escondidos",
        "<strong>Cenários Narrativos</strong> — Como escrever histórias de uso que revelam regras de negócio",
        "<strong>Fluxograma</strong> — Mapeamento visual de processos antes de propor soluções",
      ]},
    ],
    placeholder: true,
  },
];

window.ALL_SPEC_CHAPTERS = [...window.SPEC_CHAPTERS, ...window.SPEC_CHAPTERS_PT2];
